import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  serversSidebar: [
    {
      type: 'category',
      label: 'Official',
      link: { type: 'doc', id: 'official/index' },
      items: [{ type: 'autogenerated', dirName: 'official' }],
    },
    {
      type: 'category',
      label: 'Verified Partners',
      link: { type: 'doc', id: 'verified/index' },
      items: [{ type: 'autogenerated', dirName: 'verified' }],
    },
    {
      type: 'category',
      label: 'Community',
      link: { type: 'doc', id: 'community/index' },
      items: [{ type: 'autogenerated', dirName: 'community' }],
    },
  ],
};

export default sidebars;
